### ISSUE TITLE
'gg config -w subscription=' would fail to add subscription in zsh on arch linux host

### ISSUE THREAD

**Issue by Garhve** [mzz2017/gg#10]
I'm using `zsh` in my terminal.
```
$ gg --version
gg version 0.2.1
```
`gg` is fine, but when I add my subscription as document says:
```
$ gg config -w subscription='My link'
```
would result this error
```
zsh: no matches found: 'My link'
```

However, this problem seems fine with bash, I can add `My link` to `gg` in bash without any problem.
I'm not sure if this error is repeatable 'cause for now I'm just having one arch laptop. Could you kindly check it?
Thanks a lot.

**Comment by mzz2017** [comment]
I think it is just a zsh problem.

Type `setopt no_nomatch` and try again.

If it works, append the line to your ~/.zshrc

**Comment by mzz2017** [comment]
Or I think you can try to use "" instead of ''
