### ISSUE TITLE
gg bash报错

### ISSUE THREAD

**Issue by AK47-Plusone** [mzz2017/gg#11]
FATA[0003] tracer.New:fork/exec /bin/bash: operation not permitted
![image](https://user-images.githubusercontent.com/63524489/160220063-e6c377f5-f1c4-45e8-bf26-f590153e30ba.png)

**Comment by mzz2017** [comment]
请问具体如何复现？

**Comment by wenbindu** [comment]
FATA[0000] tracer.New:fork/exec /usr/bin/curl: operation not permitted  ，我也是同样问题

**Comment by wenbindu** [comment]
> 

步骤：
 sh -c "$(curl -L https://hubmirror.v2raya.org/raw/mzz2017/gg/main/release/go.sh)"
ln -s /usr/local/bin/gg /usr/bin/gg
gg curl ipv4.appspot.com

**Comment by mzz2017** [comment]
https://github.com/mzz2017/gg/actions/runs/3157376242 试一下这个
