### ISSUE TITLE
订阅地址似乎不支持，请问如何移除

### ISSUE THREAD

**Issue by lukeaust** [mzz2017/gg#12]
![image](https://user-images.githubusercontent.com/24719573/161377514-a4bbd5b2-6c36-48c4-8381-aeefdd4e7731.png)
读取不到节点，单独添加也没成功～

**Comment by mzz2017** [comment]
移除订阅的方法是 `gg config -w subscription=`
如果你使用脚本安装，移除 gg 的方法是删除 /usr/local/bin/gg 以及 ~/.local/bin/gg
