### ISSUE TITLE
请问已经支持使用https节点了吗? 我直接使用https报错

### ISSUE THREAD

**Issue by wutongskype** [mzz2017/gg#14]
root@debian11:~# gg --node https://http用户:http密码@测试网址.com:10844 -vv scp -i ~/SCPkey -rp -P 60040 /root root@测试网址.com:/root/123123_test2233
TRAC[0000] Version: v0.2.3                              
TRAC[0000] OS/Arch: linux/amd64                         
TRAC[0000] Using config file: /root/.ggconfig.toml      
TRAC[0000] Config:
test_node_before_use=true
node=https://http用户:http密码@测试网址.com:10844
subscription.link=
subscription.select=first
subscription.cache_last_node=true
cache.subscription.last_node=
no_udp= 
FATA[0000] GetDialer:unable to connect to the proxy node: connectivity test failed: Get "https://fonts.gstatic.com/generate_204": tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config 
root@debian11:~# ^C
root@debian11:~# 

经过测试,直接使用http正常,用https节点的话如上报错.
https节点是xray开的,http+tls 1.3
![image](https://user-images.githubusercontent.com/40192806/171942717-123cfad2-f7a3-4e63-9b6d-6b04903d0d3c.png)
试着换成最小tls版本1.1也还是不行.

**Comment by wutongskype** [comment]
https节点在其他环境下使用也是正常.

**Comment by mzz2017** [comment]
需要手动添加`?sni=xxx`，稍后我会修复

**Comment by mzz2017** [comment]
已修复于 https://github.com/mzz2017/gg/releases/tag/v0.2.4
谢谢！

**Comment by wutongskype** [comment]
> 已修复于 https://github.com/mzz2017/gg/releases/tag/v0.2.4 谢谢！

哇，修复的好迅速，真牛逼！

**Comment by wutongskype** [comment]
> 已修复于 https://github.com/mzz2017/gg/releases/tag/v0.2.4 谢谢！

对了，gg能否支持添加多个静态node，由于不是经常用机场订阅都是自建服务器，能添加两三个静态node就好了。比如这样给node设置个tag。命令：-t or --tag

凑活能用版：
添加节点：gg config -w tag=azhk node=vmess://MY_VMESS_SERVER_SHARE_LINK
使用节点：gg -t=azhk curl ipv4.appspot.com
删除节点：gg config del -t=azhk


相对完美版：
考虑到命令简洁，其实还有语法上的优化空间。我觉得完美整洁应该如下这样。
对于静态节点：-n = --node，-t = --tag
gg config add -t=azhk -n=vmess:// 添加节点
gg config del -t=azhk 删除节点
gg config use -t=azhk 设置azhk标签是默认节点

原来添加订阅那段我没仔细看，大概也可以归类到这样一种语法体系。-s = --sub
gg config add -t=azhk --sub=https://订阅.com
gg config del -t=azhk 删除订阅
gg config use -t=azhk 然后出现一个订阅里的节点列表，选择默认节点。

然后在使用上可以：
gg -t=azhk curl 这样指定节点标签
(此处tag若是订阅则自动选择一个一个延迟最低的节点，或者添加订阅时选择的那个节点。感觉牵扯到订阅就很麻烦囧～)
或者gg curl 这样使用默认节点

PS：我觉得订阅这块完全可以砍了，小鸡上装个v2rayA，直接gg config add -t=v2rayA -n=socks://127.0.0.1:20170(v2a默认s5端口)就完事了，或者http://:20172，v2a那个国内外分流的端口，把订阅管理，测速，选择全都扔给v2a去

**Comment by mzz2017** [comment]
> 对了，gg能否支持添加多个静态node，由于不是经常用机场订阅都是自建服务器，能添加两三个静态node就好了。比如这样给node设置个tag。命令：-t or --tag

我也是自己维护自建节点。对于这个用法，我分享一个基于 netlify 的思路：
1. 新建一个**私有**仓库。

2. 在根目录下新建文件 build.sh

   ```bash
   #!/bin/bash
   
   set -ex
   
   mkdir -p dist/sub
   ls *.src | cut -d. -f1 | sed -r '/^\s*$/d' | while read -r name; do
     cat $name.src | sed '/^#/d' | sed '/^\s*$/d' | base64 -w0 > dist/sub/$name
   done
   
   echo "/*
     Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
   " > dist/_headers
   ```
   
3. 在根目录新建文件 name_of_your_subscription.src

   ```
   # some annotate
   trojan://A_TROJAN_SHARING_LINK
   # some annotate
   ss://A_SS_SHARING_LINK
   # some annotate
   vmess://A_VMESS_SHARING_LINK
   # some annotate
   vmess://A_VMESS_SHARING_LINK
   ```

4. 在 [netlify](https://app.netlify.com/) 添加你的域名 test.example.com，在 Build & deploy - Build settings 中 设置 Build command 为 ./build.sh，publish directory 为 /dist

5. 在你修改 name_of_your_subscription.src 文件后一分钟，等待 build 完毕后，`https://test.example.com/sub/name_of_your_subscription` 即为你的订阅链接

6. 在 `gg config -w subscription=https://test.example.com/sub/name_of_your_subscription` 后，使用 `gg --select curl ip.sb` 选择节点使用

> 我觉得订阅这块完全可以砍了

每个人的使用场景不同，并不是每个人都会配合 v2rayA 等工具使用的。我一般会喜欢使用订阅。

> 考虑到国情，除了http/https 和 socks5/socks5h，建议给s5添加tls支持，比如像GOST那样：socks5+tls/socks5h+tls，socks5+tls://节点.com socks5h+tls://节点.com

目前还不支持不主流的用法。socks5+tls 不如直接上 trojan。
