### ISSUE TITLE
WSL Ubuntu

### ISSUE THREAD

**Issue by Ran-Xing** [mzz2017/gg#16]
FATA[0000] tracer.Wait:no such process

NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**Comment by mzz2017** [comment]
这个 gg 会有偶尔失败的情况，暂时没办法找到好方法解决，先保留这个 issue 吧
