### ISSUE TITLE
git fatal: early EOF

### ISSUE THREAD

**Issue by Ran-Xing** [mzz2017/gg#17]
gg git clone git@github.com:xxxxxxxx.git
Cloning into 'xxxxxxxx'...
remote: Enumerating objects: 1465, done.
remote: Counting objects: 100% (589/589), done.
remote: Compressing objects: 100% (269/269), done.
ssh_dispatch_run_fatal: Connection to 127.0.0.2 port 40931: message authentication code incorrect
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by mzz2017** [comment]
What is your node protocol?

**Comment by Ran-Xing** [comment]
@mzz2017 ssr,怎么看协议呀，这个报错，我mac 用nmap 做转发的时候也有，完全看运气的

```ssh
Host github.com
    HostName ssh.github.com
    User git
    Port 443
    TCPKeepAlive yes
    Proxycommand ncat --proxy 127.0.0.1:7890 --proxy-type socks5 %h %p
```

**Comment by mzz2017** [comment]
如果是节点不稳定的问题的话，gg也帮不了哦
