### ISSUE TITLE
[BUG] It may encounter DNS pollution when using local DNS services

### ISSUE THREAD

**Issue by cubercsl** [mzz2017/gg#2]
当用户使用本地 DNS 服务 如 `systemd-resolved` 时，他们会遇到 DNS 污染。
When someone uses local DNS services like `systemd-resolved`, they may encounter DNS pollution.

在详细的日志中可以看到 `skip loopback: 127.0.0.53:53` 的输出。
In verbose mode, it outputs: `skip loopback: 127.0.0.53:53`

**Comment by mzz2017** [comment]
Fixed. Thanks for your report!
