### ISSUE TITLE
部分订阅读取不到节点

### ISSUE THREAD

**Issue by FairyWorld** [mzz2017/gg#22]
测试了1个v2订阅, 3个clash订阅, 有一个clash订阅读取不到节点

![image](https://user-images.githubusercontent.com/32956212/192480081-0d606432-01da-4001-b81b-5590ff41c6a9.png)

**Comment by mzz2017** [comment]
你可以看看是不是节点不支持，加 `-vv`

**Comment by FairyWorld** [comment]
> -vv
有可能是, 只有一个订阅异常
![image](https://user-images.githubusercontent.com/32956212/192481983-6fd4d34b-00fc-4b7c-9efd-64f9165730ad.png)

**Comment by mzz2017** [comment]
可否将订阅内容贴出，注意隐藏关键信息。

**Comment by FairyWorld** [comment]
> 可否将订阅内容贴出，注意隐藏关键信息。

订阅的内容好像是base64一大堆字符串, 不过刚刚没有考虑到是不是中间代理导致的, 因为订阅是在国外的，我配置了个cloudflare去代理, 但是gg配置也是用了一样的地址还是没有节点。
![image](https://user-images.githubusercontent.com/32956212/192493445-c3268e63-6ead-4f25-bc6d-7e15774fab0c.png)

**Comment by mzz2017** [comment]
有文本内容吗？用浏览器打开订阅地址可得

**Comment by FairyWorld** [comment]
> 有文本内容吗？用浏览器打开订阅地址可得

![image](https://user-images.githubusercontent.com/32956212/192494641-fd28fd6a-cf83-43cf-b283-5cc035045ae1.png)
