### ISSUE TITLE
可否自定义配置节点测速地址？

### ISSUE THREAD

**Issue by FairyWorld** [mzz2017/gg#24]
经过测试有很多节点是正常的，但是测速结果是-1ms。目前还不清楚具体原因，我用了1个v2订阅，全部节点测速正常，但是后面我尝试用了3个clash订阅，所有节点都是-1ms，但是实际上clash订阅里的节点都是正常的。在gg终端也是实际可用的，只是测速异常

感觉下面几个测速地址比较好用，想自定义配置一下
![image](https://user-images.githubusercontent.com/32956212/192481377-86aecf07-afc9-418e-9186-048814496502.png)

<br/>
<br/>

clash订阅我多次测速查看了所有节点都是-1ms (v2订阅的节点测速是正常的), 但是在window多次测速中, 只有2个是挂掉的。在gg终端也是实际可用的，只是测速异常
![image](https://user-images.githubusercontent.com/32956212/192483522-2957406c-eb69-4028-b3c4-2e427c143396.png)

**Comment by mzz2017** [comment]
你的 vmess 可能 AlterID != 0，这是不被支持的。请检查。

**Comment by FairyWorld** [comment]
> 你的 vmess 可能 AlterID != 0，这是不被支持的。请检查。

不是很懂，先用着，只是测速显示异常，不影响使用

**Comment by mzz2017** [comment]
> 

意思是可以正常使用是吗？我加个选项吧

**Comment by FairyWorld** [comment]
> > 
> 
> 意思是可以正常使用是吗？我加个选项吧

是的，有可能是默认读取的节点就是可用的

**Comment by FairyWorld** [comment]
> https://github.com/mzz2017/gg/releases/tag/v0.2.12
测速配置的命令是什么

**Comment by mzz2017** [comment]
看readme

**Comment by contrun** [comment]
我也遇到了这个问题。最终发现是 clash 支持 http obfuscation. gg 似乎不支持。下面是编辑过的订阅链接的配置文件里面的服务器信息。

```
{name:🇯🇵 高级 专线 日本  01, server: xxx.example.com, port: 13221, type: ss, cipher: chacha20-ietf-poly1305, password: password, plugin: obfs, plugin-opts: {mode: http, host: e7a070d3d2.iqiyi.com}, udp: true}
```
