### ISSUE TITLE
订阅配置不成功

### ISSUE THREAD

**Issue by zeqi2000** [mzz2017/gg#31]
![图片](https://user-images.githubusercontent.com/48551609/209755886-8fb3268b-eb81-48a6-9246-cab66bbe5156.png)
请问，我配置订阅链接之后还需要额外的操作吗，这个报错好像是没有读到我的节点信息导致连接不上的意思吗，另外哪个链接才是应该选择的。事实上我试了几个都不行。。。
![图片](https://user-images.githubusercontent.com/48551609/209756064-e9746f38-c8cc-45b8-9c86-87a850149b60.png)

**Comment by mzz2017** [comment]
参数加-vv试试

**Comment by zeqi2000** [comment]
![图片](https://user-images.githubusercontent.com/48551609/209757361-58b54f09-92de-4378-9674-be0ee07d8c70.png)
![图片](https://user-images.githubusercontent.com/48551609/209757372-e296981f-5b96-464f-8cb5-62186aae9974.png)
![图片](https://user-images.githubusercontent.com/48551609/209757387-4b174dcf-ec90-4e01-bad0-41c7033409a7.png)
变成了这样

**Comment by mzz2017** [comment]
那这就是没办法访问吧，是不是被墙了，你把这个地址粘贴到浏览器去看看能不能打开

**Comment by zeqi2000** [comment]
![图片](https://user-images.githubusercontent.com/48551609/209757679-7860fe40-de24-42e7-bf8d-698675dddb3c.png)
可以的，下载链接，直接下载了

**Comment by mzz2017** [comment]
那你用 --testnode false 试试呢

**Comment by zeqi2000** [comment]
我刚刚试了下，使用订阅链接（clash，v2ray）都不行。我单独设置节点链接是可以的。

**Comment by mzz2017** [comment]
那就奇怪了哦，你浏览器能打开是不是因为挂了梯子了

**Comment by zeqi2000** [comment]
我关了梯子的，就是直接打开，（我win上，订阅是可以不挂梯子直接更新的）
设置了订阅链接，gg会自动帮忙更新吗，是不是还有一个类似于更新订阅的操作（？

**Comment by mzz2017** [comment]
如果你愿意提供测试链接，可以把链接发送我的邮箱 mzz@tuta.io

**Comment by mzz2017** [comment]
> 我关了梯子的，就是直接打开，（我win上，订阅是可以不挂梯子直接更新的）
> 
> 设置了订阅链接，gg会自动帮忙更新吗，是不是还有一个类似于更新订阅的操作（？

当前节点不可用的话会自动拉取订阅重新选一个的。
