### ISSUE TITLE
INFO[0029] exitHandler: cannot get the arguments from storehouse because of neverseen: pid: 730, inst: 174

### ISSUE THREAD

**Issue by kissablemt** [mzz2017/gg#4]
不知道什么问题噢

**Comment by mzz2017** [comment]
什么cpu架构，如何复现

**Comment by kissablemt** [comment]
树莓派arm的，gg curl 就会

**Comment by kissablemt** [comment]
> 什么cpu架构，如何复现

难得在你这找到arm，git上找了好多都不支持arm

**Comment by mzz2017** [comment]
> 难得在你这找到arm，git上找了好多都不支持arm

好的，arm还没测试过，我会测试一下然后尝试修复，谢谢

**Comment by mzz2017** [comment]
我用 qemu 模拟了一下 arm，是可以使用的，只是会有这个报错信息。你那边可以正常使用吗？

**Comment by smartcatboy** [comment]
> qemu 模拟了一下 arm

执行 `lscpu` 的输出能发一下吗？

**Comment by smartcatboy** [comment]
> 树莓派arm的，gg curl 就会

执行 `lscpu` 和 `cat /proc/cpuinfo` 的输出能发一下吗？

**Comment by kissablemt** [comment]
`lscpu`
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               3
Model name:          Cortex-A72
Stepping:            r0p3
CPU max MHz:         1500.0000
CPU min MHz:         600.0000
BogoMIPS:            108.00
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32

`cat /proc/cpuinfo`
processor	: 0
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 1
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 2
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

processor	: 3
model name	: ARMv7 Processor rev 3 (v7l)
BogoMIPS	: 108.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd08
CPU revision	: 3

Hardware	: BCM2711
Revision	: c03111
Serial		: 10000000244a543c
Model		: Raspberry Pi 4 Model B Rev 1.1

**Comment by mzz2017** [comment]
请尝试该版本是否已修复：https://github.com/mzz2017/gg/actions/runs/1552478468

**Comment by kissablemt** [comment]
> 请尝试该版本是否已修复：https://github.com/mzz2017/gg/actions/runs/1552478468

太感谢啦！！可以啦！！
另外想问问，如何使用socks5？
`gg config node`
```log
socks5://127.0.0.1:1089
```

然后`gg curl cip.cc`
```log
FATA[0000] GetDialer:unable to connect to the proxy node: connectivity test failed: Get "https://fonts.gstatic.com/generate_204": EOF
```

**Comment by mzz2017** [comment]
我稍后尝试一下

**Comment by mzz2017** [comment]
我这里没什么问题，如果节点没问题的话可能是不支持 UDP，试试添加 `--noudp`。

**Comment by kissablemt** [comment]
> 我这里没什么问题，如果节点没问题的话可能是不支持 UDP，试试添加 `--noudp`。

我这边试了,`gg --noudp --node socks5://127.0.0.1:1089 curl cip.cc`，有时成功，但大部分都是
```log
curl: (52) Empty reply from server
```
或者
```log
curl: (56) Recv failure: Connection reset by peer
```
但是`gg --noudp --node socks5://192.168.0.111:1089 curl cip.cc`，就是使用局域网另一台机子的socks就成功了，不太清楚什么问题哎

**Comment by kissablemt** [comment]
发现了，两次`gg --noudp --node socks5://127.0.0.1:1089 curl cip.cc`运行间隔比较短，就会出现问题

**Comment by kissablemt** [comment]
```log
[2021-12-08 16:29:01] [ERROR] 127.0.0.1:50624 unknown protocol
[2021-12-08 16:29:01] [INFO] 127.0.0.1:50624 disconnected, 0 bytes received, 0 bytes sent, lasted for 0 seconds
```
这是trojan的日志

**Comment by mzz2017** [comment]
> 这是trojan的日志

你是说你使用 socks5 接本地的 v2ray 出口按 trojan 发出去就会出现问题是吗，这是服务器端的日志还是？

> 发现了，两次gg --noudp --node socks5://127.0.0.1:1089 curl cip.cc运行间隔比较短，就会出现问题

我按照你的方法没有成功复现

**Comment by kissablemt** [comment]
> > 这是trojan的日志
> 
> 你是说你使用 socks5 接本地的 v2ray 出口按 trojan 发出去就会出现问题是吗，这是服务器端的日志还是？
> 
> > 发现了，两次gg --noudp --node socks5://127.0.0.1:1089 curl cip.cc运行间隔比较短，就会出现问题
> 
> 我按照你的方法没有成功复现

我是开的[https://github.com/trojan-gfw/trojan](trojan-gfw)，然后开放了本地端口为1089，直接socks连过去的。直接export测试过是可以的。
那个日志是trojan-gfw里client端的日志

**Comment by mzz2017** [comment]
已修复于 https://github.com/mzz2017/gg/releases/tag/v0.1.12

**Comment by kissablemt** [comment]
非常感谢！！
