### ISSUE TITLE
有如下报错，是kernel差东西吗

### ISSUE THREAD

**Issue by Windrunner20** [mzz2017/gg#61]
> root@armbian:~# gg git clone --depth=1 https://github.com/torvalds/linux.git
WARN[0000] error when get ptrace scope: open /proc/sys/kernel/yama/ptrace_scope: no such file or directory 
FATA[0000] GetDialer:unable to connect to the proxy node: connectivity test failed: Get "https://connectivitycheck.gstatic.com/generate_204": version 72 is not supprted

**Comment by mzz2017** [comment]
@Windrunner20 你是不是把 socks5 代理写成 http 地址了

**Comment by Windrunner20** [comment]
已经解决了，我把自建节点换成机场订阅就正常了，速度也正常，感谢！！
