### ISSUE TITLE
problem in installing (or using)

### ISSUE THREAD

**Issue by shaomh225** [mzz2017/gg#63]
hi, I am so sorry to disturb your recent works. I find this command-line proxy tool recently, and I try to install this tool today. However, it doesn't work. can you give me some advices about how to solve this problem or what mistakes I have made?
(I can find the $PATH for gg, and its $PATH is also in my setting. and the mirror doesn't work, so I copied the gg.sh into local file)
<img width="1355" alt="截屏2023-11-21 13 16 45" src="https://github.com/mzz2017/gg/assets/97825442/2a05dd32-c1b5-4984-a7e2-ab90cdbc6d24">

**Comment by mzz2017** [comment]
@shaomh225 command -v gg

**Comment by shaomh225** [comment]
> @shaomh225 command -v gg

<img width="461" alt="截屏2023-11-21 16 49 37" src="https://github.com/mzz2017/gg/assets/97825442/77901f00-413f-4c91-983c-402ba98c69f7">
it still doesn't work

**Comment by shaomh225** [comment]
> ls -lh /usr/local/bin/gg
> 
> file /usr/local/bin/gg
> 
> uname -a

![Uploading 截屏2023-11-21 18.21.45.png…]()

**Comment by mzz2017** [comment]
@shaomh225 看不见

**Comment by shaomh225** [comment]
<img width="1316" alt="截屏2023-11-21 18 21 45" src="https://github.com/mzz2017/gg/assets/97825442/773a6628-756e-4819-af69-78c09535b201">

**Comment by mzz2017** [comment]
@shaomh225 看起来是空文件，没安装上，releases里下一个替换一下

**Comment by shaomh225** [comment]
> @shaomh225 看起来是空文件，没安装上，releases里下一个替换一下

好的，我试一下

**Comment by shaomh225** [comment]
> @shaomh225 看起来是空文件，没安装上，releases里下一个替换一下

可以了！非常感谢，给你添麻烦了。
