### ISSUE TITLE
unable to set CAP_SETFCAP effective capability: Operation not permitted

### ISSUE THREAD

**Issue by UranusITS** [mzz2017/gg#65]
我在尝试不带root权限在zsh中从`go.sh`安装gg，遇到了这个报错。

应该是来自安装脚本的这一行

https://github.com/mzz2017/gg/blob/640a4325055d4e29baeabc6b3029f02ec389f519/release/go.sh#L90

但是我没能查找到无需sudo权限运行这一行的方法。直接注释掉这一行是可行的吗？我对setcap不是很熟悉，不是很明白会对安装产生的影响

**Comment by mzz2017** [comment]
@UranusITS 可以忽略这个

**Comment by UranusITS** [comment]
使用起来没有问题，非常感谢👍
