### ISSUE TITLE
gitee 支持

### ISSUE THREAD

**Issue by zeqi2000** [mzz2017/gg#73]
当服务器本来就连不上外网，连不上github时，此时安装不了gg。

故希望增加国内代码托管方案，如 gitee 之类

**Comment by zeqi2000** [comment]
@mzz2017 大佬作者，鄙人搬运了一下，安装命令，**sudo sh -c "$(curl -L https://gitee.com/tendermoon/gg_clone/raw/main/release/go.sh)"** 方便大家使用，您看可以不

**Comment by mzz2017** [comment]
> @mzz2017 大佬作者，鄙人搬运了一下，安装命令，**sudo sh -c "$(curl -L https://gitee.com/tendermoon/gg_clone/raw/main/release/go.sh)"** 方便大家使用，您看可以不

我印象里 gitee 是实名的，需不需要低调一点？如果直接宣传使用这个会不会有问题？

**Comment by zeqi2000** [comment]
> > @mzz2017 大佬作者，鄙人搬运了一下，安装命令，**sudo sh -c "$(curl -L https://gitee.com/tendermoon/gg_clone/raw/main/release/go.sh)"** 方便大家使用，您看可以不
> 
> 我印象里 gitee 是实名的，需不需要低调一点？如果直接宣传使用这个会不会有问题？

啊，这方面欠考虑了，还是删了吧，感谢提醒

**Comment by zeqi2000** [comment]
欠考虑了，已删除

**Comment by mzz2017** [comment]
@zeqi2000 done
