### ISSUE TITLE
添加clash订阅 没可用节点

### ISSUE THREAD

**Issue by Wan9299** [mzz2017/gg#90]
![屏幕截图 2024-11-16 042342](https://github.com/user-attachments/assets/37f8f978-4d74-482f-9d0b-fd4dbf9c120b)

我的订阅在clash 里是正常可用的 不太明白哪里出了问题 大佬救命!!

**Comment by moyvbai** [comment]
同问，我的也是同样的问题

**Comment by ShiraishiMa1** [comment]
gg不支持你用的订阅的协议吧
